kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloud-app
  namespace: default
  labels:
    app: cloud-app
  annotations:
    deployment.kubernetes.io/revision: '327'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cloud-app
      annotations:
        kubectl.kubernetes.io/restartedAt: '2024-06-27T09:43:36.027726941Z'
        kubesphere.io/creator: admin
        kubesphere.io/imagepullsecrets: '{}'
        kubesphere.io/restartedAt: '2024-06-27T08:43:23.926Z'
    spec:
      containers:
        - name: cloud-app
          image: vittolibre/cloud-app
          env:
            - name: DB_URL
              value: 'jdbc:postgresql://192.168.1.33:32751/cloud'
            - name: DB_USER
              value: cloudadmin
            - name: DB_PASSWORD
              value: cloud
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      serviceAccountName: cloud.app.cpzrb
      serviceAccount: cloud.app.cpzrb
      nodeName: worker
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
