kind: Deployment
apiVersion: apps/v1
metadata:
  name: edge-app-db
  namespace: default
  labels:
    app: edge-app-db
  annotations:
    deployment.kubernetes.io/revision: '7'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-app-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: edge-app-db
      annotations:
        kubesphere.io/creator: admin
        kubesphere.io/imagepullsecrets: '{}'
        kubesphere.io/restartedAt: '2024-06-15T15:04:51.135Z'
    spec:
      containers:
        - name: edge-app-db
          image: vittolibre/gateway-db
          ports:
            - name: http-0
              containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cloud-db-credentials
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: edgenode
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
